# ==========================================
# Notification Service Configuration
# ==========================================

# Application name
spring.application.name=notification-service

# Port on which notification service will run
server.port=8084

# ==========================================
# Database Configuration
# ==========================================

# MySQL database connection URL
spring.datasource.url=jdbc:mysql://localhost:3306/notificationservice_db

# MySQL credentials
spring.datasource.username=root
spring.datasource.password=root1234

# MySQL driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA / Hibernate Configuration
# ==========================================

# WARNING: change to validate or none in production
spring.jpa.hibernate.ddl-auto=update

# WARNING: disable in production
spring.jpa.show-sql=true

# Tell Hibernate we are using MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==========================================
# Kafka Configuration
# ==========================================

# Kafka broker address
spring.kafka.bootstrap-servers=localhost:9092

# Consumer group ID
spring.kafka.consumer.group-id=notification-group

# Read messages from beginning if no offset exists
spring.kafka.consumer.auto-offset-reset=earliest

# Deserialize keys as strings
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Deserialize values as JSON
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Actual deserializers
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Trust all packages for deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Map OrderEvent class
spring.kafka.consumer.properties.spring.json.value.default.type=com.shopsphere.notificationservice.dto.OrderEvent

# ==========================================
# Email Configuration
# ==========================================

# Gmail SMTP server
spring.mail.host=smtp.gmail.com

# Gmail SMTP port
spring.mail.port=587

# Your Gmail address
spring.mail.username=jaysinhzala1@gmail.com

# Your Gmail app password
spring.mail.password=tbtlnudoycjkwzcx


# Enable STARTTLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==========================================
# Security Configuration
# ==========================================

# Disable security - API Gateway handles authentication
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration