# ==========================================
# API Gateway Configuration
# ==========================================

# Application name
spring.application.name=api-gateway

# Port on which API Gateway will run
server.port=8080

# ==========================================
# JWT Configuration
# ==========================================

# Secret key used to validate JWT tokens
jwt.secret=${JWT_SECRET}